const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
  GET_ALL_CUSTOMER_FILES: "GET_ALL_CUSTOMER_FILES",
};
export default ACTIONS;
